# Generated by Django 3.2.16 on 2023-01-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.CharField(max_length=5)),
                ('sex', models.CharField(max_length=5)),
                ('self_attribute', models.CharField(max_length=20)),
                ('partner_attribute', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='holding',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='rates',
            name='currency',
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Holding',
        ),
        migrations.DeleteModel(
            name='Rates',
        ),
    ]
