# Generated by Django 3.2.16 on 2023-01-19 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20230119_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='character',
            field=models.CharField(max_length=50),
        ),
    ]
