# Generated by Django 3.2.16 on 2023-01-19 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_attribute_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='character',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(max_length=20),
        ),
    ]
