# Generated by Django 3.2.16 on 2023-01-21 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_accountholder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountholder',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='accountholder',
            name='user_visited',
        ),
        migrations.AddField(
            model_name='accountholder',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='partner_attribute',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='self_attribute',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='accountholder',
            name='sex',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='accountholder',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
