# Generated by Django 3.2.16 on 2023-01-21 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20230121_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='age',
            field=models.IntegerField(),
        ),
    ]
