# Generated by Django 3.2.16 on 2023-01-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20230121_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountholder',
            name='age',
            field=models.IntegerField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
